name: Export

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Setup Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.5.3'
      - name: Get the scripts
        run: |
          wget https://raw.githubusercontent.com/paveloom-m/julialang-slack-history/main/export.jl
          wget https://raw.githubusercontent.com/paveloom-m/julialang-slack-history/main/check.jl
          wget https://raw.githubusercontent.com/paveloom-m/julialang-slack-history/main/Project.toml
      - name: Instantiate the project
        run: julia --project=. -e 'using Pkg; pkg"instantiate"'
      - name: Export the history
        run: |
          julia --project=. export.jl
          julia --project=. check.jl
      - name: Import the GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.GPG_PASSWORD }}
          git-user-signingkey: true
          git-commit-gpgsign: true
      - name: Create and push a commit
        run: |
          touch file
          git add -A
          git commit -m "Update the history [auto]."
          git push
