name: Parsing Tests

on:
  pull_request:
    branches:
      - main

env:
  TOKEN: ${{ secrets.SLACK_TOKEN }}

jobs:
  CheckCommit:
    name: Check the commit
    runs-on: ubuntu-latest
    outputs:
      subject: ${{ steps.get.outputs.subject }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get the subject of the last commit
        id: get
        run: |
          SUBJECT=$(git log --format=%s -n 1 HEAD^2)
          echo ${SUBJECT}
          echo "::set-output name=subject::${SUBJECT}"
  Test:
    name: Run the tests
    runs-on: ubuntu-latest
    needs: CheckCommit
    if: ${{ !contains(needs.CheckCommit.outputs.subject, '[no tests]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: '1.5.3'
      - name: Instantiate the project
        run: julia --project=. -e 'using Pkg; pkg"instantiate"'
      - name: Test the first run
        run: |
          julia --project=. export.jl
          julia --project=. check.jl
      - name: Test the second run
        run: |
          julia --project=. export.jl
          julia --project=. check.jl
